#!/bin/bash

process_page() {
    # convert this page into temp
    pandoc --template=boiler/template.latex -o pdf/$1.tex $1.md
    
    # TODO we need special formatting for input inside of pre output blocks, so we made some thingies
    #sed -i 's/INPUTSTART/<span class="input">/' pdf/$1.tex
    #sed -i 's/INPUTEND/<\/span>/' pdf/$1.tex

    # convert the latex into a pdf
    cd pdf; pdflatex --interaction=batchmode $1.tex; cd ..
    cd pdf; pdflatex --interaction=batchmode $1.tex; cd ..
    cd pdf; pdflatex --interaction=batchmode $1.tex; cd ..
    
    # remove unneeded output files
    rm pdf/*.aux pdf/*.log
}

# make a fresh pdf output directory
rm -rf pdf
mkdir -p pdf

# make a link to the images directory so html pages can refer to them
if [ ! -L pdf/images ]
then
    cd pdf && ln -s ../images ./images && cd ..
fi

# render all the pages from markdown -> tex -> pdf
#process_page title
#process_page preface
process_page chapter01
#process_page chapter02
#process_page chapter03
#process_page chapter04
#process_page chapter05
#process_page chapter06
#process_page chapter07
#process_page chapter08
#process_page chapter09
#process_page chapter10
#process_page chapter11


