#!/bin/bash

process_page() {
    # convert this page into temp
    pandoc -o ./temp.tex $1.md
    
    # start by dumping in the boilerplate preamble, and building the navbar
    cat boiler/preamble.tex >> pdf/$1.tex

    # TODO we need special formatting for input inside of pre output blocks, so we made some thingies
    #sed -i 's/INPUTSTART/<span class="input">/' ./temp.tex
    #sed -i 's/INPUTEND/<\/span>/' ./temp.tex

    # now dump the content, followed by postamble
    cat ./temp.tex >> pdf/$1.tex
    cat boiler/postamble.tex >> pdf/$1.tex

    # clean up
    rm -f ./temp.tex 
    
    # convert the latex into a pdf
    cd pdf; pdflatex --interaction=batchmode $1.tex; cd ..
    cd pdf; pdflatex --interaction=batchmode $1.tex; cd ..
    cd pdf; pdflatex --interaction=batchmode $1.tex; cd ..
    
    # remove unneeded output files
    rm pdf/*.aux pdf/*.log
}

# make the pdf directory if it's not there
mkdir -p pdf

# make a link to the images directory so html pages can refer to them
if [ ! -L pdf/images ]
then
    cd pdf && ln -s ../images ./images && cd ..
fi

# render all the pages from markdown -> tex -> pdf
process_page title
process_page preface
process_page chapter01
process_page chapter02
process_page chapter03
process_page chapter04
process_page chapter05
process_page chapter06
process_page chapter07
process_page chapter08
process_page chapter09
process_page chapter10
process_page chapter11


